### ISSUE TITLE
Incorrect CD Track Count when switching CDs

### ISSUE THREAD

**Issue by helgo1506** [jfchapman/VUPlayer#22] opened 2021-07-16 08:18 UTC
Hey there,

First of all, i'm very happy, that you updated your player. I'm using your Player now for over 15 years already, cause my old PCs back in the days couldnt handle the "modern" players out there well together with gaming :P 

Okay, to the issue :

When you input a Audio CD with 3 Tracks for example and switch to a CD with more Tracks, it dont load at all or only list till the count of the previous CD (3 Tracks before, next CD is 5 but still only shows 3 from 5)
When i restart the programm it's correct again.

Keep it up ! I will still use your Player xD

**Comment by jfchapman** [comment] 2021-07-17 12:58
Hi!

I wasn't able to reproduce this issue (I tried ejecting a CD with 9 tracks, then loading a CD with 13 tracks).
When you say switching CDs, are you switching between multiple drives? If that's the case, then it'll probably have to wait until I get another external drive to test with.

One bug I did notice was that you can delete CD tracks from the list with the delete key, which you shouldn't be able to. They do show up again on a restart (or ejecting/loading the disc), but I'll tidy that up for the next version.

Thanks,
James

**Comment by helgo1506** [comment] 2021-07-18 22:33
Hmm, im using Win7 64bit. Sometimes even when no CD is loaded at first it dont load it at all. I tested it with a program of my own and it works there. Didnt looked into the source what your using, but im using the window msg "WM_DEVICECHANGE" with testing the wparm value for "DBT_DEVICEARRIVAL" and "DBT_DEVICEREMOVECOMPLETE" , which works pretty fine. It happends with the my physical drive. I got 1 physical DVD/CD drive and 3 virtual drives from deamon tools. Dont know if this helps.

PS : It even seems like it dont even recognize my cd switching.

**Comment by jfchapman** [comment] 2022-05-28 12:13
It's taken awhile, but a finally got around to getting a couple of extra external CD drives to test with. 
I couldn't reproduce the exact issue of seeing the wrong track count, but it did reveal some related issues and performance problems, so these have hopefully now been resolved in v4.14.

**Closed as completed by jfchapman** 2022-05-28 12:13 UTC
